---
# Grafana Installation <START>
- name: Install Grafana Packages
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Grafana GPG Key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add Grafana Repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
# Grafana Installation <END>


# Promethues Installation <START>
- name: Install Prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
# Promethues Installation <END>


# Influxdb Installation <START>
- name: Add Influxdate Key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present    

- name: Install Influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: yes
# Influxdb Installation <END>

#-----Configuration-----# 

# Grafana Start <START>
- name: Start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
# Grafana Start <END>

# Prometheus Start <START>
- name: Start Prometheus
  service:
     name: prometheus 
     state: started
# Prometheus Start <END>

# Influxdb Start <START>
- name: Start Influxdb
  service:
     name: influxdb
     state: started
# Influxdb Start <END>


# tasks file for roles/ubuntu/Grafana
