---
# Grafana Installation <START>
- name: Add Grafana Repository
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/

- name: Install Grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes
# Grafana Instalaation <END>

# Prometheus Installation <START>
- name: Add Prometheus Repository
  copy:
    src: prometheus.repo
    dest: /etc/yum.repos.d/

- name: Install Prometheus
  yum:
    name: prometheus
    state: latest
    update_cache: yes
# Prometheus Installation <END>

# Influxdb Installation <START>
- name: Add Influxdb Repository
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d/

- name: Install Influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes
# Influxdb Installation <END>

#-----Configuration-----#

# Grafana Config <START>
- name: Start grafana
  service:
    name: grafana-server
    state: started
# Grafana Config <END>

# Prometheus Config <START>
- name: Start Prometheus
  service: 
    name: prometheus
    state: started
# Prometheus Config <END>

# Influxdb Config <START>
- name: Start Influxdb
  service:
    name: influxdb
    state: started
# Influxdb Config <END>



# tasks file for roles/centos/grafana
